[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "16"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200